export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const GET_STORES='GET_STORES'
export const GET_STORES_FAILURE='GET_STORES_FAILURE'
export const GET_STORES_SUCCESS='GET_STORES_SUCCESS'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'

export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'
